// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Checkpoint struct {
	ID           int       `json:"id"`
	Title        string    `json:"title"`
	Instructions string    `json:"instructions"`
	Links        []string  `json:"links"`
	IsCompleted  *bool     `json:"isCompleted"`
	Roadmap      *Roadmap  `json:"roadmap"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type NewCheckpoint struct {
	Title        string `json:"title"`
	Instructions string `json:"instructions"`
	RoadmapID    int    `json:"roadmapId"`
}

type NewRoadmap struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatorID   int    `json:"creatorId"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID                int        `json:"id"`
	Username          string     `json:"username"`
	Email             string     `json:"email"`
	Password          string     `json:"password"`
	FollowingRoadmaps []*Roadmap `json:"followingRoadmaps"`
	CreatedRoadmaps   []*Roadmap `json:"createdRoadmaps"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
}
