// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckpointStatus struct {
	UserID       int    `json:"userId"`
	CheckpointID int    `json:"checkpointId"`
	RoadmapID    int    `json:"roadmapId"`
	Status       string `json:"status"`
}

type FollowRoadmap struct {
	UserID    int `json:"userId"`
	RoadmapID int `json:"roadmapId"`
}

type GetRoadmap struct {
	ID int `json:"id"`
}

type GetUser struct {
	ID int `json:"id"`
}

type Login struct {
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password string  `json:"password"`
}

type NewCheckpoint struct {
	Title        string   `json:"title"`
	Instructions string   `json:"instructions"`
	Links        []string `json:"links"`
	RoadmapID    int      `json:"roadmapId"`
}

type NewRoadmap struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatorID   int    `json:"creatorId"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateStatus struct {
	CheckpointID int    `json:"checkpointId"`
	Status       string `json:"status"`
}
