// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddCheckpoint struct {
	RoadmapID    int `json:"roadmapId"`
	CheckpointID int `json:"checkpointId"`
}

type FollowRoadmap struct {
	RoadmapID int `json:"roadmapId"`
}

type GetRoadmap struct {
	RoadmapID int `json:"roadmapId"`
}

type GetUser struct {
	UserID int `json:"userId"`
}

type NewCheckpoint struct {
	Title        string `json:"title"`
	Instructions string `json:"instructions"`
	RoadmapID    int    `json:"roadmapId"`
}

type NewRoadmap struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatorID   int    `json:"creatorId"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
