name: Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: roadmap
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Run go
        run: go mod tidy && go build cmd/roadmap/main.go && ./main &
      - name: Restore db
        uses: tj-actions/pg-restore@v4.5
        with:
          database_url: "postgres://postgres:postgres@localhost:5432/roadmap"
          backup_file: "database/dev/1_schema.sql"
      - name: Restore db 2
        uses: tj-actions/pg-restore@v4.5
        with:
          database_url: "postgres://postgres:postgres@localhost:5432/roadmap"
          backup_file: "database/dev/2_data.sql"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          install: npm run install
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000, http://localhost:8080"
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
