name: Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # working-directory: web
          install: make install-web
          build: make build-web
          start: make air, make start-web
          wait-on: "http://localhost:3000, http://localhost:8080"
