name: Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # working-directory: web
          install: npm --prefix ./web run install
          build: npm --prefix ./web run build
          start: make air, npm --prefix ./web start
          wait-on: "http://localhost:3000, http://localhost:8080"
