name: Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          install: npm run install
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
